openapi: 3.0.3
info:
  description: Platform for creating reservations
  title: Reservations
  version: 1.0.0
paths:
  /reserve:
    post:
      operationId: createReservation
      tags:
        - reservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reservation"
      responses:
        "201":
          description: reservation created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/reservation"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /alive:
    get:
      operationId: isAlive
      tags:
        - healthcheck
      responses:
        "200":
          description: API is alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthcheck"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /ready:
    get:
      operationId: isReady
      tags:
        - healthcheck
      responses:
        "200":
          description: API is ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthcheck"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    reservation:
      type: object
      required:
        - item_name
        - item_quantity
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        item_name:
          type: string
          minLength: 1
          maxLength: 100
        item_quantity:
          type: integer
          format: int32
          minimum: 1
    healthcheck:
      type: string
    error:
      type: object
      required:
        - message
        - code
      properties:
        code:
          type: integer
          format: int
        message:
          type: string